---
title: "Modèle matrice et applications en écologie"
bibliography: "Quentin, Alexie, Jeanne et Laurane"
execute: 
  freeze: auto
output: 
  html_document:
   toc: true
   toc_float: true
---

Plan projet : 

I. Modélisation matricielle en écologie -> Laurane
A quoi servent les matrices en écologie ?
Transformer une population en matrice
Modifier une matrice de population (addition de population,soustraction)

II. Les grands exemples de matrices en écologie  -> Alex
Classes d’âge et reproduction : Matrice de Leslie
Impact prédateur
Compétition ?

III. Matrice en épidémiologie -> Jeanne

IV. Chaînes de Markov -> Quentin


II/ 
Nous retrouvons maintenant notre famille de suricates 10 ans plus tard. Pendant cette décennie notre population a bien évolué et 
différentes classes d’âges se sont formées. 
Nous avons tout d’abord la classe des juvéniles, notés J qui ont entre 0 et 1 an et qui correspondent aux individus ne possédant pas encore la maturité sexuelle. 
Il n’y qu’une petite partie de ces juvéniles qui parviennent à atteindre la classe d’âge adulte, en suivant un taux de passage noté TPa.
Ensuite nous passons à la classe d’âge des adultes, notés A, qui eux peuvent se reproduire avec un taux de fécondité noté TFa et qui ont tous entre 1 et 10 ans. 
Les femelles suricates adultes survivent d’une année sur l’autre avec un taux de survie noté TSa et il n’y qu’une petite partie de ces femelles qui 
parviennent à atteindre la classe d’âge sénior, en suivant un taux de passage noté TPs. 
Pour le bien de notre histoire, nous allons considérer qu’a partir de 10 ans nos suricates adultes appartiennent à la classe d’âge des seniors, notés S et qu’ils 
ont un taux de fécondité inférieur à celui des adultes, notés TFs.
Les femelles suricates seniors survivent d’une année sur l’autre avec un taux de survie noté TSs. 

Avec toutes ces informations nous pouvons dessiner l’arbre de vie suivant : 

(mettre figure en latex)

Figure 2 : Cycle de vie des suricates

Pour le compléter on estime que : 
-	une femelle suricate adulte va avoir en moyenne 3 petits par an
-	environ 90% des femelles suricates adultes survivent une année sur l’autre, jusqu’à sa dixième année. 
-	une femelle suricate senior va avoir en moyenne 1 petit par an 
-	40 % des femelles suricates seniors qui sont encore vivantes à la fin de onzième année vont survivre, mais pas au-delà d’une douzième année.
-	un juvénile sur deux ne survit pas à sa première année de vie
-	30% des femelles suricates adultes atteignent le stade sénior 
Avec toutes ces informations nous pouvons ainsi compléter notre cycle de vie :

Figure 3 : Cycle de vie des suricates complété 

Si nous notons, pour tout instant t (le temps étant compté en années, de sorte que t est entier), Jt le nombre de suricates juvéniles, 
At celui des adultes et St celui des séniors on aura ainsi :

$$
N_t = J_t + A_t + S_t
$$

le nombre total de suricates dans la population étudiée.
 
Les hypothèses ci-dessus se traduisent par les équations suivantes : 

$$
\begin{align*}
J_{t+1} &= 0 \cdot J_t + TF_a \cdot A_t + TF_s \cdot S_t \\
A_{t+1} &= TP_a \cdot J_t + TS_a \cdot A_t + 0 \cdot S_t \\
S_{t+1} &= 0 \cdot J_t + TP_s \cdot A_t + TS_s \cdot S_t
\end{align*}
$$

Nous pouvons ensuite remplacer par nos valeurs : 

$$
\begin{align*}
J_{t+1} &= 0 \cdot J_t + 3 \cdot A_t + 1 \cdot S_t \\
A_{t+1} &= 0.5 \cdot J_t + 0.9 \cdot A_t + 0 \cdot S_t \\
S_{t+1} &= 0 \cdot J_t + 0.3 \cdot A_t + 0.4 \cdot S_t
\end{align*}
$$

Ce deuxième systeme nous permet ainsi d'établir une matrice.
L'utilisation d'une matrice nous permettra par la suite de déterminer différents paramètres comme le taux de croissance par exemple,
afin de comprendre et de prédire l'évolution de la population dans le temps.
Cette type de matrice a un nom : la matrice de Leslie. 
Le terme "matrice de Leslie" fait référence à l'économiste et démographe britannique Patrick Leslie, qui a introduit cette méthode de 
modélisation démographique dans les années 1940. Initialement développé pour étudier la croissance des populations d'insectes,
elle a ensuite été adaptée et étendue pour être appliquée à la modélisation démographique humaine et animale.

Ainsi, nous pouvons créer cette matrice : 

$$
\begin{bmatrix}
0 & TF_a & TF_s \\
TP_a & TS_a & 0 \\
0 & TP_s & TS_s \\
\end{bmatrix}
$$

Cette matrice est construite de telle sorte à ce que en colonne nous ayons dans l'ordre Jt+1, At+1, St+1 et en ligne Jt, At et St. 
Vous remarquerez ainsi que nous avons sur la première ligne les indicateurs concernant la fécondité de nos individus notés TF.
Sur la diagonale nous aurons parmaètres concernant la survie et sur la diagnoale en dessous ceux concernant les probabilité de passer
d'un stade d'âge, à un autre. 

Ainsi, si nous remplaçons par nos valeurs nous obtenons ainsi la matrice suivante :  

$$
\begin{bmatrix}
0 & 3 & 1 \\
0.5 & 0.9 & 0 \\
0 & 0.3 & 0.4 \\
\end{bmatrix}
$$

Maintenant que nous avons notre matrice nous allons pouvoir la rentrer sur le logiciel R afin de pouvoir faire différents calculs 
que nous detaillerons plus tard : 

Pour rentrer et donc créer notre matrice sur R nous allons écrire les lignes suivantes : 

$$
TF_a = 3
TF_s = 1
TP_a = 0.5
TS_a = 0.9
TP_s = 0.3
TS_s = 0.4
leslie<-c(0,TF_a,TF_s,TP_a,TS_a,0,0,TP_s,TS_s) 
# Avec cette ligne de code nous avons donc créé notre liste nommée leslie, qui comprend tous les paramètres présents dans notre cycle de vie
matrice<-matrix(data=leslie, nrow = 3,ncol = 3, byrow=TRUE, dimnames = ) 
# La fonction matrix() nous permet de transformer cette liste en matrice
$$ 

Ensuite, afin d'effectuer tous les calculs en lien avec notre matrice, nous devons installer un package qui s'appelle popbio

$$
install.packages("popbio")
library(popbio)
$$

Grâce à ce package nous pourrons calculer différents paramètres...

Le premier paramètre que nous allons calculer est le taux de croissance. 
Le taux de croissance est un indicateur démographique qui permet de connaître l'évolution d'une population à un moment donné. 
En l'occurence, dans notre exemple on l'obtient ainsi : 

$$
taux de croissance = lambda(matrice)
$$

On obtient ainsi un taux de croissance de 1.795362. 
Notre taux de croissance est supérieur à 1, ce qui indique que notre population augmente. 
Ce type de taux est généralement associé à des facteurs tels qu'un taux de natalité élevé, une faible mortalité, des migrations nettes positives,
ou une combinaison de ces éléments. Cela indique ainsi que notre population est dynamique et que notre population est en croissance démographique. 
Si le taux de croissance avait été inférieur à 1, cela indiquerait que notre population est en déclin. 
Généralement dans ces types de taux de croissance sont souvent associés à des populations vieillissantes, à des tendances démographiques négatives.
Ce qui n'est pas le cas dans notre population de surricat. 

Maintenant que nous savons que notre population est en croissance démographique, nous allons regarder le temps de génération. 
Le temps de génération correspond au temps moyen pour que chaque individus soit remplacé dans la population. 
Nous allons donc utiliser la fonction generation.time() qui est disponible dans le package popbio. 

```{r}
temps_de_generation = generation.time(matrice)
# 4.890923
```

Dans notre cas, le pas de temps que nous avons pris est de 1 an donc nous avons un temps de génération de 4.8 ans.
Le temps de génération représente la durée moyenne entre la naissance d'une génération parentale et la naissance de la génération suivante, 
ce qui nous permet ainsi d'avoir une perspective sur la manière dont les caractéristiques démographiques se transmettent à travers les générations.

On va desormais calculer la structure d'âge stable qui sera sous forme de proportion par classe d'âge et permettent de représenter la répartition attendue des différents 
groupes d'âge dans une population stationnaire. Pour obtenir ces proportions, on suppose généralement que la population est stable dans le sens où le nombre de naissances,
le nombre de décès et le nombre de migrants sont équilibrés et que la distribution par âge reste constante. 

Pour les calculer on fait :  

$$
stable.stage(matrice)
# 0.59577168 0.33269876 0.07152956
$$

Ainsi, selon l'hypothèse d'une population stable il faudrait : 60% de juvéniles 33% d'adultes et 0.07% de séniors

On peut représenter cette structure d'âge stable en faisant : 

$$
barplot(stable.stage(matrice),names.arg=c("juvénile","adulte","senior"),ylim = c(0,0.7))
$$

On peut aussi calculer les valeurs reproductives à chaque classe d'âge, ce qui va nous permettre d'évaluer la contribution de chaque groupe d'âge à la 
reproduction et à la croissance de la population.
La valeur reproductive d'une classe d'âge est calculée en tenant compte des taux de survie et des taux de reproduction spécifiques à chaque classe d'âge. 
Elle représente le nombre moyen de descendants qu'un individu d'une classe d'âge particulière peut s'attendre à produire au cours de sa vie.

On peut donc écrire : 

$$
reproductive.value(matrice)
# 1.0000000 3.5907241 0.7166599
$$

On obtient ainsi : 1 correspond à l'indice de base (classe juvénile), 3.59 (classe adulte), 0.71 (classe sénior). 
Etant donne que les juvéniles ne peuvent pas se reproduire, on ne prend pas en compte cette classe là, d'où le 1. 
On voit bien que ce sont les adultes qui contribuent le plus à la reproduction et que les séniors contribuent un tout petit peu. 

On peut ensuite calculer le temps qu'il faudra à notre population pour se remettre d'une perturbation.
Ce concept est important car il est souvent lié à la notion de résilience démographique. La résilience démographique se réfère à la capacité d'une population à 
récupérer après avoir subi des perturbations telles que des catastrophes naturelles, des épidémies, des changements environnementaux, ou d'autres événements susceptibles
d'affecter la structure ou la taille de la population.

Pour ce faire on fait : 

$$
damping.ratio(matrice)
# on obtient 2.23 qu'on multiplie par le temps de generation
damping.ratio(matrice)*generation.time(matrice)
# on obtient 10.89126
$$

On voit ainsi, qu'il faudrait environ 11 ans à notre population pour se remettre d'une perturbation comme une catastrophe naturelle, un changement environnemental etc...

Maintenant que nous avons vu comment se comportait notre population, nous allons regarder des projections sur différentes tailles de population.

Tout d'abord, quand la population est dans un état proche de la population stable, soit 60% de juvéniles, 33% d'adultes et 7% de séniors. 
Dans un premier temps on va partir sur un pas de temps de 20.  

$$
pop.projection(matrice,c(60,33,7),20) #proche de la stucture stable
#on entre le nom de la matrice, un vecteur avec l'effectif initial de chaque classe et le nbr de pas de temps
#on obtient des tailles de population par année (popsize) et les taux de croissance (popchanges)
# $pop.sizes
# [1]     100.000     178.400     321.520     576.352    1035.510    1858.521    3337.200    5991.095   10756.497
# [10]   19311.554   34671.435   62247.613  111757.133  200644.407  360229.435  646742.179 1161136.405 2084660.164
# [19] 3742719.735 6719536.860

# $pop.changes
# [1] 1.784000 1.802242 1.792585 1.796663 1.794787 1.795622 1.795246 1.795414 1.795339 1.795373 1.795357 1.795364
# [13] 1.795361 1.795362 1.795362 1.795362 1.795362 1.795362 1.795362
$$ 

Ainsi, on voit avec les pop.sizes qu'au bout de 19 ans, en situtation stable, on aurait une population de 6719536.860 individus et que le taux de croissance 
passerait de 1.784000 à 1.795362. 

Et si on fait durer cette simulation sur 100 pas de temps on obtient alors : 

$$
pop.projection(matrice,c(60,33,7),100)
$$

On passerait alors d'un effectif initial de 1.000000e+02 individus à un effectif de 1.443784e+27 individus. 
Pour ce qui est du taux de croissance on passerait de 1.784000 à 1.795362.

On observe ainsi une croissance très importante de cette population. 

Néanmoins, cette situation de population stable n'est pas représentatrice de la réalité. 
Donc essayons avec d'autres effectics initiaux, avec une structure déséquilibrée. 

$$
pop.projection(matrice,c(1,4,2),20) #structure désequilibrée
pop.projection(matrice,c(1,4,2),100)
$$

Dans ce cas là, on observe aussi une croissance très importante de notre population.
Pour pouvoir différencier les deux, on fait des représentations graphiques.   

$$
#sur 20 ans pour la taille population
plot((pop.projection(matrice,c(60,33,7),20)$pop.sizes),type="l",ylim=c(100,100000),ylab="taille de pop",xlab="année")
lines(pop.projection(matrice,c(1,4,2),20)$pop.sizes,type="l",col="red")
legend("topright",legend=c("equilibre","desequilibre"),text.col=c("black","red")) 

#sur 100ans pour la taille population
plot((pop.projection(matrice,c(60,33,7),100)$pop.sizes),type="l",xlim = c(0,30), ylim=c(100,10000000),ylab="taille de pop",xlab="année")
lines(pop.projection(matrice,c(1,4,2),100)$pop.sizes,type="l",col="red")
legend("topright",legend=c("equilibre","desequilibre"),text.col=c("black","red"))  

#sur 20 ans pour le taux de croissance
plot((pop.projection(matrice,c(60,33,7),20)$pop.changes),type="l",xlim = c(0,10),ylim=c(1,3),ylab="taux de croissance réalisé",xlab="année")
lines(pop.projection(matrice,c(1,4,2),20)$pop.changes,type="l",col="red")
legend("bottomright",legend=c("equilibre","desequilibre"),text.col=c("black","red"))

#sur 100ans pour le taux de croissance
plot((pop.projection(matrice,c(60,33,7),100)$pop.changes),type="l",xlim = c(0,10),ylim=c(1,3),ylab="taux de croissance réalisé",xlab="année")
lines(pop.projection(matrice,c(1,4,2),100)$pop.changes,type="l",col="red")
legend("bottomright",legend=c("equilibre","desequilibre"),text.col=c("black","red")) 
$$

Enfin, à l'aide de la fonction elasticity(), on va pouvoir voir que taux va le plus contribuer à l'évoltuion de notre population : 

$$
elasticity(matrice)
# on obtient cette nouvelle matrice là
#           [,1]       [,2]        [,3]
# [1,] 0.0000000 0.30186317 0.021633323
# [2,] 0.3234965 0.32517220 0.000000000
# [3,] 0.0000000 0.02163332 0.006201494
$$

Grâce à cette nouvelle matrice on voit que :
- On a des 0 là où on avait des 0 dans la matrice de base. 
- Le plus grand chiffre, soit 0.32517220, correspond au taux de survie des adultes, ce qui signifie que c'est ce taux là qui va avoir le plus d'impact sur le lambda.
- Le second, soit 0.3234965, correspond au taux de passage de juvénile à adulte ensuite c'est le taux de fécondité des adultes etc...

Pour finir, il est aussi possible de simuler des perturbations directement avec la matrice de base et on aurait ceci : 

$$
# Si on diminue la survie des adultes de 30% par exemple
TF_a = 3
TF_s = 1
TP_a = 0.5
TS_a = 0.9*0.3
TP_s = 0.3
TS_s = 0.4
leslie<-c(0,TF_a,TF_s,TP_a,TS_a,0,0,TP_s,TS_s) 
matrice<-matrix(data=leslie, nrow = 3,ncol = 3, byrow=TRUE, dimnames = ) 
lambda(matrice)
$$

Dans ce cas on observe ainsi une diminution du lambda de 0.36 etc...